name: 01. Respotiory Setup Python actions

inputs:
  json_repository_list:
    description: 'Path to JSON file containing the list of repositories to set up'
    required: true
    default: './json/repository_list.json'
  github_token:
    description: 'GitHub token for authentication'
    required: true
    

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v4
      with:
        # Cache pip's HTTP/cache directory so repeated pip installs are faster
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('./01_repo_setup/python/repo_setup/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ./01_repo_setup/python/repo_setup/requirements.txt

    - name: Setup Repositories
      shell: bash
      run: python ./01_repo_setup/python/repo_setup/repo_setup.py --json_repository_list "${{ inputs.json_repository_list }}" --github_token "${{ inputs.github_token }}"
