name: 01. Respotiory Setup Python actions

inputs:
  json_repository_list:
    description: 'Path to JSON file containing the list of repositories to set up'
    required: true
    default: './json/repository_list.json'
  github_token:
    description: 'GitHub token for authentication'
    required: true
    

runs:
  using: 'composite'
  steps:
    - name: Setup Repositories
      shell: bash
      run: python ./01_repo_setup/python/repo_setup/repo_setup.py --json_repository_list "${{ inputs.json_repository_list }}" --github_token "${{ inputs.github_token }}"
